"""Add the Agent Host schema.

This is the single migration for the whole Agent Host feature: identity
(pairings, hosts, harnesses), run dispatch (commands, run leases), and the
runtime-profile columns that bind a profile to a harness. Deployments therefore
apply one revision, not a chain of them.

It is additive apart from three removals, each of which the downgrade recreates
exactly: the redundant per-table ``id`` indexes listed in
``_TABLES_WITH_REDUNDANT_ID_INDEX``, the ``agent_runtime_daemons`` table, and
the ``agent_runtime_profiles.daemon_id`` foreign key into it.

Those two go because the legacy local daemon is gone from the code: nothing maps
the table or the column any more, so leaving them would make the next
autogenerated revision open with a ``DROP TABLE`` nobody wrote. The profile's
other legacy columns - ``protocol``, ``kind`` and ``profile_metadata`` - are
still read by the runtime-profile mapping and stay.

Run events are not journaled here. They travel a per-run Redis Stream, so there
is no ``agent_host_events`` table and no ack-watermark column on the lease: the
stream's last entry is the watermark. Redis has no persistence in this
deployment, so losing the stream is not fully recoverable - the host resends
what it still holds and the backend adopts that sequence rather than refusing
it, which is a resync, not a replay from the beginning.

Revision ID: 0009_agent_host
Revises: 0008_function_execution
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "0009_agent_host"
down_revision = "0008_function_execution"
branch_labels = None
depends_on = None


UUID = postgresql.UUID(as_uuid=True)
JSONB = postgresql.JSONB(astext_type=sa.Text())



def _created_columns() -> list[sa.Column]:
    return [
        sa.Column("id", UUID, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    ]


def _audit_columns() -> list[sa.Column]:
    return [
        *_created_columns(),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    ]


# Every declarative base used to declare `id` as primary_key=True AND
# index=True, so each table carried a plain btree on `id` on top of the unique
# index PostgreSQL already builds for the primary key. The duplicate was
# maintained on every insert and could never be chosen over the PK index. The
# bases no longer set it; this drops the ones already in the schema.
#
# Drop and restore both iterate the SAME pinned list below. An earlier version
# derived the drop from pg_index at runtime, which would have removed any
# single-column index on a column named `id` anywhere in the schema - including
# tables this feature knows nothing about - while the restore only recreated
# the pinned ones. That asymmetry made the downgrade lossy for anything the
# authors had not seen.
# The set of tables carrying ix_<table>_id at revision 0008 that still exist
# after this one. Pinned rather than derived, so a downgrade restores precisely
# what was there: five tables with an id primary key never had the duplicate.
#
# `agent_runtime_daemons` carried one too but is deliberately absent, because
# this revision drops that table outright. Restoring its index belongs with the
# table itself in the downgrade - listing it here would instead try to index a
# table that has not been recreated yet.
_TABLES_WITH_REDUNDANT_ID_INDEX = (
    "accounts",
    "agent_approval_decisions",
    "agent_conversations",
    "agent_feedback",
    "agent_messages",
    "agent_runs",
    "agent_runtime_profiles",
    "agent_surface_conversation_links",
    "agent_surface_external_users",
    "agent_surfaces",
    "agents",
    "app_releases",
    "apps",
    "auth_configs",
    "auth_permissions",
    "connect_requests",
    "connector_operations",
    "connector_triggers",
    "connectors",
    "datastore_files",
    "datastore_tables",
    "function_runs",
    "functions",
    "organization_invitations",
    "organization_members",
    "organizations",
    "pod_join_requests",
    "pod_members",
    "pods",
    "resource_permission_grants",
    "role_assignments",
    "role_permissions",
    "roles",
    "schedules",
    "usage_limit_counters",
    "usage_records",
    "users",
    "workflow_flow_runs",
    "workflow_flows",
    "workflow_run_waits",
)


def _drop_redundant_id_indexes() -> None:
    for table_name in _TABLES_WITH_REDUNDANT_ID_INDEX:
        op.execute(sa.text(f'DROP INDEX IF EXISTS "ix_{table_name}_id"'))


def _restore_redundant_id_indexes() -> None:
    """Recreate the duplicates so the downgrade is faithful."""
    for table_name in _TABLES_WITH_REDUNDANT_ID_INDEX:
        op.execute(
            sa.text(
                f'CREATE INDEX IF NOT EXISTS "ix_{table_name}_id" '
                f'ON "{table_name}" (id)'
            )
        )


def _restore_legacy_daemon_schema() -> None:
    """Recreate ``agent_runtime_daemons`` and the profile column pointing at it.

    Mirrors the definition in revision 0001 exactly, including the redundant
    ``ix_agent_runtime_daemons_id`` that revision 0008 still carried. The rows
    are gone for good - this restores the shape, not the data, which is the most
    a downgrade can offer for a table the feature deletes.
    """
    op.create_table(
        "agent_runtime_daemons",
        sa.Column("user_id", UUID, nullable=False),
        sa.Column("device_key", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("device_info", JSONB, nullable=False),
        sa.Column("harness_catalog", JSONB, nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disconnected_at", sa.DateTime(timezone=True), nullable=True),
        *_audit_columns(),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "device_key",
            name="uq_agent_runtime_daemon_user_device",
        ),
    )
    op.create_index(
        "ix_agent_runtime_daemons_id", "agent_runtime_daemons", ["id"]
    )
    op.create_index(
        "ix_agent_runtime_daemons_status", "agent_runtime_daemons", ["status"]
    )
    op.create_index(
        "ix_agent_runtime_daemons_user_id", "agent_runtime_daemons", ["user_id"]
    )
    op.create_index(
        "ix_agent_runtime_daemons_user_status",
        "agent_runtime_daemons",
        ["user_id", "status"],
    )

    op.add_column(
        "agent_runtime_profiles", sa.Column("daemon_id", UUID, nullable=True)
    )
    op.create_index(
        "ix_agent_runtime_profiles_daemon_id",
        "agent_runtime_profiles",
        ["daemon_id"],
    )
    # 0001 declared this foreign key inline and unnamed, so PostgreSQL derived
    # the name below. Naming it explicitly reproduces that exactly.
    op.create_foreign_key(
        "agent_runtime_profiles_daemon_id_fkey",
        "agent_runtime_profiles",
        "agent_runtime_daemons",
        ["daemon_id"],
        ["id"],
        ondelete="SET NULL",
    )


def upgrade() -> None:
    op.create_table(
        "agent_host_pairings",
        *_created_columns(),
        sa.Column("user_id", UUID, nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_hash", name="uq_agent_host_pairing_code_hash"),
    )
    # (user_id, expires_at) also serves lookups keyed on user_id alone, so no
    # separate single-column index is created here.
    op.create_index(
        "ix_agent_host_pairing_user_expires",
        "agent_host_pairings",
        ["user_id", "expires_at"],
    )

    op.create_table(
        "agent_hosts",
        *_audit_columns(),
        sa.Column("user_id", UUID, nullable=False),
        sa.Column("installation_id", sa.String(length=255), nullable=False),
        sa.Column("host_secret_hash", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("protocol_version", sa.Integer(), nullable=True),
        sa.Column("host_release", sa.String(length=128), nullable=False),
        sa.Column("capacity", JSONB, nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        # One row per person per machine. A paired computer belongs to the
        # person who paired it, so re-pairing the same installation updates it
        # rather than creating a second row for one physical machine.
        sa.UniqueConstraint(
            "user_id",
            "installation_id",
            name="uq_agent_host_user_installation",
        ),
        sa.UniqueConstraint("host_secret_hash", name="uq_agent_host_secret_hash"),
    )
    # Status-only lookups drive the offline sweep across all users, so this is
    # not covered by (user_id, status) below.
    op.create_index("ix_agent_hosts_status", "agent_hosts", ["status"])
    op.create_index("ix_agent_host_user_status", "agent_hosts", ["user_id", "status"])

    op.create_table(
        "agent_host_harnesses",
        *_audit_columns(),
        sa.Column("host_id", UUID, nullable=False),
        sa.Column("harness_key", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("adapter_version", sa.String(length=128), nullable=False),
        sa.Column("upstream_version", sa.String(length=128), nullable=True),
        sa.Column("health", sa.String(length=64), nullable=False),
        sa.Column("capabilities", JSONB, nullable=False),
        sa.Column("config_revision", sa.String(length=255), nullable=False),
        sa.Column("config_options", JSONB, nullable=False),
        sa.Column("stale_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stale_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["host_id"], ["agent_hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id", "harness_key", name="uq_agent_host_harness_key"),
    )
    op.create_index(
        "ix_agent_host_harnesses_host_id", "agent_host_harnesses", ["host_id"]
    )

    op.create_table(
        "agent_host_commands",
        *_created_columns(),
        sa.Column("host_id", UUID, nullable=False),
        sa.Column("run_id", UUID, nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("lease_epoch", sa.BigInteger(), nullable=True),
        sa.Column("payload", JSONB, nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection", JSONB, nullable=True),
        sa.ForeignKeyConstraint(["host_id"], ["agent_hosts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Drives the competitive FOR UPDATE SKIP LOCKED handout in poll_commands.
    op.create_index(
        "ix_agent_host_command_poll",
        "agent_host_commands",
        ["host_id", "state", "created_at"],
    )
    op.create_index(
        "ix_agent_host_command_run",
        "agent_host_commands",
        ["run_id", "lease_epoch"],
    )

    # run_id is the primary key, which is what makes double-dispatch of a run
    # structurally impossible rather than merely guarded in application code.
    op.create_table(
        "agent_host_run_leases",
        sa.Column("run_id", UUID, nullable=False),
        sa.Column("host_id", UUID, nullable=False),
        sa.Column("harness_id", UUID, nullable=False),
        sa.Column("runtime_profile_id", UUID, nullable=True),
        sa.Column("lease_epoch", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["host_id"], ["agent_hosts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["harness_id"], ["agent_host_harnesses.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["runtime_profile_id"],
            ["agent_runtime_profiles.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    # (host_id, state) also serves host_id-only lookups.
    op.create_index(
        "ix_agent_host_run_lease_host_state",
        "agent_host_run_leases",
        ["host_id", "state"],
    )
    op.create_index(
        "ix_agent_host_run_lease_expiry",
        "agent_host_run_leases",
        ["lease_expires_at"],
        postgresql_where=sa.text(
            "state NOT IN ('WAITING_INPUT','SUCCEEDED','FAILED',"
            "'CANCELLED','DISPATCH_UNKNOWN')"
        ),
    )

    # Profile binding. Both columns are nullable so existing rows, including
    # legacy daemon profiles, stay valid without a backfill.
    op.add_column(
        "agent_runtime_profiles",
        sa.Column("runtime_type", sa.String(length=32), nullable=True),
    )
    op.add_column(
        "agent_runtime_profiles",
        sa.Column("harness_id", UUID, nullable=True),
    )
    op.create_foreign_key(
        "fk_agent_runtime_profiles_harness",
        "agent_runtime_profiles",
        "agent_host_harnesses",
        ["harness_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(
        "ix_agent_runtime_profiles_harness_id",
        "agent_runtime_profiles",
        ["harness_id"],
    )
    # Holds for legacy rows too: runtime_type IS NULL takes the first branch,
    # which only requires harness_id to be NULL.
    op.create_check_constraint(
        "ck_agent_runtime_profile_harness_binding",
        "agent_runtime_profiles",
        "(runtime_type IS DISTINCT FROM 'HARNESS' AND harness_id IS NULL) OR "
        "(runtime_type = 'HARNESS' AND harness_id IS NOT NULL)",
    )

    # Retire the legacy local daemon. The column goes first because it holds the
    # only foreign key into the table; dropping it takes that constraint and
    # ix_agent_runtime_profiles_daemon_id with it, which frees the table itself.
    op.drop_column("agent_runtime_profiles", "daemon_id")
    op.drop_table("agent_runtime_daemons")

    _drop_redundant_id_indexes()


def downgrade() -> None:
    _restore_redundant_id_indexes()
    _restore_legacy_daemon_schema()

    op.drop_constraint(
        "ck_agent_runtime_profile_harness_binding",
        "agent_runtime_profiles",
        type_="check",
    )
    op.drop_index(
        "ix_agent_runtime_profiles_harness_id",
        table_name="agent_runtime_profiles",
    )
    op.drop_constraint(
        "fk_agent_runtime_profiles_harness",
        "agent_runtime_profiles",
        type_="foreignkey",
    )
    op.drop_column("agent_runtime_profiles", "harness_id")
    op.drop_column("agent_runtime_profiles", "runtime_type")

    op.drop_table("agent_host_run_leases")
    op.drop_table("agent_host_commands")
    op.drop_table("agent_host_harnesses")
    op.drop_table("agent_hosts")
    op.drop_table("agent_host_pairings")
