const style = `<style>*{box-sizing:border-box}body{margin:0}section{padding:20px;background:var(--lemma-widget-surface,#fff);color:var(--lemma-widget-text,#202723);font:14px/1.5 var(--lemma-widget-font,system-ui);border:1px solid var(--lemma-widget-border,#ddd);border-radius:12px}header{display:flex;justify-content:space-between;gap:12px;margin-bottom:16px}h3{font-size:17px;font-weight:500;margin:0}small,footer{color:var(--lemma-widget-muted,#626962);font-size:12px}table{border-collapse:collapse;width:100%;font-size:13px}td,th{text-align:left;padding:10px 0;border-bottom:1px solid var(--lemma-widget-border,#ddd);font-weight:400}td:last-child{text-align:right}th{color:var(--lemma-widget-muted,#626962)}footer{margin-top:14px}progress{width:100%;height:8px;accent-color:#426552}blockquote{margin:12px 0;padding-left:14px;border-left:3px solid var(--lemma-widget-border,#ddd)}.bars{display:grid;grid-template-columns:85px 1fr 25px;gap:10px;align-items:center}.bar{height:13px;background:#739587}strong{font-weight:500}.warn{color:var(--lemma-widget-danger,#9b432a)}</style>`;
const contents: Record<string, string> = {
    remy: `<header><h3>Northstar is waiting on us</h3><small>Due Friday</small></header><table><tr><th>Buyer</th><td>Anita · Procurement</td></tr><tr><th>Promised</th><td>Approved security overview</td></tr><tr><th>Last conversation</th><td>Tuesday’s demo</td></tr><tr><th>Next step</th><td>Review the prepared reply</td></tr></table><blockquote>“Can you send the security overview before our procurement review on Friday?”</blockquote><footer>Reply drafted for your review.</footer>`,
    june: `<header><h3>Harbor’s first import</h3><small>3 of 5 steps complete</small></header><progress value="3" max="5" aria-label="Three of five onboarding steps complete"></progress><table><tr><td>Account access</td><td>Complete</td></tr><tr><td>Source file received</td><td>Complete</td></tr><tr><td>Columns mapped</td><td>Complete</td></tr><tr><td>Validate sample</td><td class="warn">Date formats conflict</td></tr><tr><td>First full import</td><td>Waiting</td></tr></table><footer>Original file preserved · Training reminder held.</footer>`,
    scout: `<header><h3>What stalled these trials?</h3><small>5 interviews</small></header><div class="bars"><span>Setup effort</span><div class="bar" style="width:100%"></div><strong>3</strong><span>Budget</span><div class="bar" style="width:33%"></div><strong>1</strong><span>No owner</span><div class="bar" style="width:33%"></div><strong>1</strong></div><blockquote>“We ran out of time mapping our export.”<br><small>Birch · Interview B2</small></blockquote><footer>Small, selected sample. Compare converted trials before drawing a broader conclusion.</footer>`,
};
export function conversationWidget(id: string) { return style + `<section>${contents[id] ?? "<h3>Ready for a first responsibility</h3>"}</section>`; }

/* ── Kit's feedback loop: the widgets in its conversation ───────────── */

const kitStyle = `<style>.tag{display:inline-block;white-space:nowrap;font-size:12px;border-radius:6px;padding:1px 7px;background:var(--lemma-widget-subtle,#f1f1ee);color:var(--lemma-widget-muted,#626962)}.tag.bad{color:var(--lemma-widget-danger,#9b432a)}.tag.wait{color:var(--lemma-widget-warning,#8a5a12)}.tag.info{color:var(--lemma-widget-info,#2f5d8a)}.tag.ok{color:var(--lemma-widget-success,#2f6e4f)}td.n,th.n{text-align:right;font-variant-numeric:tabular-nums;padding-right:16px;white-space:nowrap}td:last-child,th:last-child{text-align:left}svg{vertical-align:middle;margin-left:8px}.none{color:var(--lemma-widget-danger,#9b432a)}td small{display:block;color:var(--lemma-widget-muted,#626962);font-size:12px}.split{display:grid;grid-template-columns:1fr auto 1fr;gap:14px;align-items:center}.split small{display:block;color:var(--lemma-widget-muted,#626962);font-size:12px}.split>div{border:1px solid var(--lemma-widget-border,#ddd);border-radius:10px;padding:10px 12px}.split .was{border-style:dashed}.split .to{display:grid;gap:8px;border:0;padding:0}.split .to>div{border:1px solid var(--lemma-widget-border,#ddd);border-radius:10px;padding:9px 12px;display:flex;justify-content:space-between;gap:10px;align-items:center}@media(max-width:560px){.split{grid-template-columns:1fr}.split>span{justify-self:center;transform:rotate(90deg)}}</style>`;

/** Seven days of reports for a theme, as a line: rising is the problem. */
function spark(days: number[], tone: string) {
    const max = Math.max(...days, 1);
    const points = days.map((value, i) => (i * 8).toFixed(0) + "," + (16 - (value / max) * 13).toFixed(1)).join(" ");
    return `<svg width="48" height="18" viewBox="0 0 48 18" aria-hidden="true"><polyline points="${points}" fill="none" stroke="var(--lemma-widget-${tone})" stroke-width="1.5" stroke-linejoin="round"/></svg>`;
}

/** The nine themes as Kit first grouped them, on Tuesday afternoon. */
const TUESDAY: [string, string, number, number[], string, string, string, string][] = [
    ["Large imports time out", "Imports over 10k rows", 38, [1, 2, 2, 4, 5, 7, 9], "Slack · email", "No fix", "bad", ""],
    ["Bulk edit missing", "Feature ask", 24, [3, 2, 4, 3, 4, 3, 5], "Slack", "No ticket", "bad", ""],
    ["App feels stuck", "Unclear cause", 14, [0, 1, 1, 2, 3, 3, 4], "In app", "Unclear", "wait", ""],
    ["Dates import as text", "Locale parsing", 22, [2, 4, 3, 5, 3, 3, 2], "Slack", "PR #482 in review", "info", "Dev"],
    ["Notifications on mobile", "No push when an import finishes", 19, [1, 2, 2, 3, 3, 4, 4], "In app · Slack", "PR #490 in review", "info", "Dev"],
    ["Login link expired", "", 31, [6, 5, 4, 2, 1, 1, 0], "Email", "Shipped", "ok", "Dev"],
    ["Column mapping resets", "", 27, [5, 4, 4, 3, 1, 0, 1], "Slack", "Shipped", "ok", "Alex"],
    ["Duplicate rows on re-import", "", 22, [4, 4, 3, 2, 1, 0, 0], "Slack · email", "Shipped", "ok", "Dev"],
    ["Wrong timezone in emails", "", 17, [3, 3, 2, 2, 1, 1, 0], "Email", "Shipped", "ok", "Alex"],
];

const kitWidgets: Record<string, string> = {
    themes: `<header><h3>Feedback themes</h3><small>${TUESDAY.reduce((sum, row) => sum + row[2], 0)} reports · 30 days</small></header><table><tr><th>Theme</th><th class="n">Reports</th><th>From</th><th>Fix</th><th>Owner</th></tr>${TUESDAY.map(([theme, why, count, days, from, fix, tone, owner]) => `<tr><td>${theme}${why ? `<small>${why}</small>` : ""}</td><td class="n">${count}${spark(days, tone === "ok" ? "success" : tone === "info" ? "info" : "danger")}</td><td><small>${from}</small></td><td><span class="tag ${tone}">${fix}</span></td><td>${owner || `<span class="none">No owner</span>`}</td></tr>`).join("")}</table><footer>Lines show the last 7 days. Open Feedback loop to work on them.</footer>`,
    replies: `<header><h3>Retry replies · PR #482</h3><small>22 drafted · 0 sent</small></header><table><tr><th>Reporter</th><th>Where</th><th>Plan</th><th>Goes via</th><th>State</th></tr><tr><td>@maria.k</td><td><small>#feedback thread</small></td><td>Pro</td><td>Kit</td><td><span class="tag wait">Waits for Dev</span></td></tr><tr><td>@tomasz</td><td><small>#feedback thread</small></td><td>Free</td><td>Kit</td><td><span class="tag wait">Waits for Dev</span></td></tr><tr><td>Northfield</td><td><small>email</small></td><td>Enterprise</td><td>Sam</td><td><span class="tag info">With Sam</span></td></tr><tr><td>@jun.ho</td><td><small>#feedback thread</small></td><td>Pro</td><td>Kit</td><td><span class="tag wait">Waits for Dev</span></td></tr><tr><td>Brightpath</td><td><small>#feedback thread</small></td><td>Enterprise</td><td>Sam</td><td><span class="tag info">With Sam</span></td></tr></table><footer>+17 more · 19 via Kit, 3 via Sam · nothing goes out until Dev confirms #482 is live</footer>`,
    resorted: `<header><h3>Re-sorted</h3><small>“App feels stuck” · 14 reports</small></header><div class="split"><div class="was"><small>Before</small><div>App feels stuck</div><small>14 reports · no owner · unclear</small></div><span aria-hidden="true">→</span><div class="to"><div><span>Notifications on mobile<small>11 from mobile · PR #490 in review</small></span><span class="tag info">+11 → 31</span></div><div><span>Large imports time out<small>Dev · P0 · 3 sample files</small></span><span class="tag bad">+3 → 41</span></div></div></div>`,
};

/** One of Kit's widgets, by name. */
export function kitWidget(name: "themes" | "replies" | "resorted") { return style + kitStyle + `<section>${kitWidgets[name]}</section>`; }
