/** Fictional, inspectable work for the public sample. Never customer data. */
export const teammates = [
    { id: "kit", name: "Kit", role: "Runs the feedback loop", icon: "/teammates/loop-v1.png", app: "Feedback loop", promise: "Every user hears back when their problem is fixed, and only once it’s live.", waiting: "19 replies wait on Dev · 1 theme has no owner", job: "Run Acme’s feedback loop. Read every report from Slack, email and the app, group them into themes, link each theme to its ticket and fix, and flag what nobody owns. When a fix ships, draft a reply for everyone who reported it; replies go out only after the engineer who shipped it confirms it’s live.", learned: "Enterprise accounts hear from their CSM (Sam). On mobile, “stuck” means Notifications, not timeouts (Dev). Retry replies wait for the PR’s author to confirm it’s live. Priority is reports × paying accounts.", ask: "Our #feedback channel is a mess. I want the biggest themes, which ones have a fix, and what nobody is working on. And when a fix ships, tell the people who reported it.", reply: "Done. 214 reports, 9 themes. 4 have a fix shipped, 2 have a fix in review, 3 have nothing.\n\nThe biggest gap: imports over 10k rows time out. 38 reports, no ticket, no owner.\n\nFrom now on I file every new message in #feedback as it lands. When a PR that fixes a theme merges, I draft the retry replies, and they go out once Dev confirms the fix is live.", items: [] },
    { id: "remy", name: "Remy", role: "Sales follow-through", icon: "/teammates/pleat-v1.png", app: "Deal desk", promise: "Every promising conversation gets a next step.", waiting: "1 buyer waiting on us", job: "Track buyer commitments, prepare relevant follow-ups, and keep every opportunity’s next step current. Ask before sending or changing pricing.", learned: "Anita is Northstar’s buyer; Raj is the technical evaluator. Check recent colleague conversations before proposing another follow-up. Only use approved security documents.", ask: "Who’s waiting on us?", reply: "Northstar asked for our security overview on Tuesday. I’ve prepared a reply with the approved document; their procurement deadline is Friday. I’m holding the Cedar follow-up because Priya spoke with them yesterday. Harbor has signed: June has the promised first-import outcome.", items: [
        { title: "Northstar · Security overview", status: "Waiting for us", owner: "Priya", detail: "To: Anita\n\nHi Anita — following up on Tuesday’s call, here’s the approved security overview for your procurement review. Raj’s deployment questions are covered in section 3. Let us know what else your team needs ahead of Friday.\n\nAttachment: Security overview — approved September edition", source: "Tuesday demo notes · Anita’s procurement email", action: "Mark draft reviewed" },
        { title: "Cedar · Evaluation", status: "Follow-up held", owner: "Priya", detail: "Priya spoke with Cedar yesterday. They are testing with their operations team on Thursday.\n\nNext step: check for their result on Friday. A reminder today would duplicate Priya’s conversation.", source: "Priya’s account note · Sept 22", action: "Confirm Friday check-in" },
        { title: "Harbor · Signed", status: "Handed to June", owner: "June", detail: "Purchased for weekly customer imports. Success means importing a validated customer file.\n\nJune has the call notes, sample requirements, and customer owner. No custom integration was promised.", source: "Signed scope · Sales handoff", action: "Acknowledge handoff" },
    ] },
    { id: "june", name: "June", role: "Customer onboarding", icon: "/teammates/frame-v1.png", app: "Customer launchpad", promise: "I’ll stay until each customer gets their first useful result.", waiting: "1 import needs help", job: "Tailor each onboarding plan to the sold outcome. Track inputs, prepare help, and escalate blockers with evidence. Ask before changing scope or delivery commitments.", learned: "Setup is not success. Harbor needs a validated customer import. Hold training reminders while a blocking import error remains unresolved.", ask: "Is Harbor ready for training?", reply: "Not yet. Setup is complete, but their first import failed because the date column uses mixed formats. I’ve prepared a corrected sample and an escalation for Dev. The training reminder is held until the import works.", items: [
        { title: "Harbor · First customer import", status: "Blocked", owner: "Dev", detail: "Goal: one validated customer import.\nCompleted: account access, source file received, columns mapped.\nBlocked: dates mix DD/MM/YYYY and YYYY-MM-DD.\n\nPrepared: a normalized 10-row sample for Dev to validate. Keep the original file unchanged.", source: "Import error log · Harbor sample, Sept 23", action: "Assign diagnosis to Dev" },
        { title: "Harbor · Training session", status: "Reminder held", owner: "Priya", detail: "Training depends on a successful sample import. Sending the reminder now would ask the customer to prepare for a workflow they cannot yet use.\n\nNext: confirm Dev’s validation, then agree a training time with the customer.", source: "Onboarding plan · Import dependency", action: "Confirm hold" },
        { title: "Cedar · Onboarding preparation", status: "Plan drafted", owner: "June", detail: "Cedar is still evaluating. The draft plan is internal until the deal closes.\n\nFirst outcome: one weekly operations report. Inputs needed: example report, source export, and the customer’s report owner.", source: "Remy’s evaluation notes", action: "Review draft plan" },
    ] },
    { id: "scout", name: "Scout", role: "Customer researcher", icon: "/teammates/extended/gem.png", app: "Evidence notebook", promise: "Keep important questions connected to evidence.", waiting: "1 finding to challenge", job: "Investigate bounded customer questions. Keep source excerpts, competing explanations, and uncertainty visible. Revisit findings when evidence changes.", learned: "Repeated comments are signals, not proof. Separate setup effort from price objections. Preserve counterexamples and show the sample size with every conclusion.", ask: "Why are our trials stalling?", reply: "In this sample of five lost-deal conversations, three mention setup effort. One names budget and one lacks an internal owner. This does not establish the main cause across all trials. June’s import blockers suggest a guided-onboarding experiment worth testing.", items: [
        { title: "Question · Why do trials stall?", status: "Working hypothesis", owner: "Scout", detail: "Setup effort appears in 3 of 5 reviewed conversations. Budget appears in 1; lack of an internal owner appears in 1.\n\nLimit: small, selected sample of lost deals. We have not compared successful trials.\n\nNext: compare five converted trials before treating this as a broader pattern.", source: "Research sample · Five fictional interview notes", action: "Request converted-trial comparison" },
        { title: "Evidence · Setup effort", status: "3 source excerpts", owner: "Scout", detail: "Northstar: ‘We need someone to walk us through the first file.’\nBirch: ‘We ran out of time mapping our export.’\nElm: ‘The import errors left us unsure what to fix.’\n\nCounterexample — Pine: ‘The workflow fits; this quarter’s budget doesn’t.’", source: "Interview notes N1, B2, E3, P4 · Sample data", action: "Flag selection bias" },
        { title: "Experiment · Guided first import", status: "Proposed", owner: "Priya", detail: "Offer guided first-import support to the next five eligible trials. Record completion, time to first result, and support effort.\n\nCompare with the previous cohort cautiously: account size and source complexity may differ. Priya decides whether to run the experiment.", source: "June’s blocker report + lost-deal review", action: "Queue for Priya’s review" },
    ] },
];
export function teammateFor(id: string) { return teammates.find(person => person.id === id) ?? teammates[0]; }
