"""initial agentbox state

Revision ID: 24278caff64b
Revises:
Create Date: 2026-07-22 20:10:36.882522
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "24278caff64b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocations",
        sa.Column("allocation_id", sa.Uuid(), nullable=False),
        sa.Column("workload_kind", sa.String(length=16), nullable=False),
        sa.Column("logical_id", sa.Uuid(), nullable=False),
        sa.Column("allocation_token", sa.Uuid(), nullable=False),
        sa.Column("provider_name", sa.String(length=32), nullable=False),
        sa.Column("provider_scope", sa.String(length=256), nullable=False),
        sa.Column("provider_id", sa.String(length=256), nullable=True),
        sa.Column("provider_instance_id", sa.String(length=256), nullable=True),
        sa.Column("profile_name", sa.String(length=128), nullable=False),
        sa.Column("profile_digest", sa.String(length=71), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("admission_class", sa.String(length=32), nullable=False),
        sa.Column("admission_state", sa.String(length=16), nullable=False),
        sa.Column("allocation_epoch", sa.BigInteger(), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("retry_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("destroyed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('reserved', 'provisioning', 'unknown', 'active', 'quiescing', 'released', 'draining', 'destroying', 'destroyed', 'error')",
            name=op.f("ck_allocations_allocation_state"),
        ),
        sa.CheckConstraint(
            "admission_state IN ('unreserved', 'reserved', 'active', 'released')",
            name=op.f("ck_allocations_admission_state"),
        ),
        sa.CheckConstraint(
            "workload_kind IN ('workspace', 'function')",
            name=op.f("ck_allocations_workload_kind"),
        ),
        sa.PrimaryKeyConstraint("allocation_id", name=op.f("pk_allocations")),
        sa.UniqueConstraint(
            "allocation_token", name=op.f("uq_allocations_allocation_token")
        ),
        sa.UniqueConstraint(
            "provider_scope", "provider_id", name="allocation_provider_id"
        ),
    )
    with op.batch_alter_table("allocations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_allocations_owner",
            ["workload_kind", "logical_id", "state"],
            unique=False,
        )

    op.create_table(
        "sandboxes",
        sa.Column("workload_kind", sa.String(length=16), nullable=False),
        sa.Column("logical_id", sa.Uuid(), nullable=False),
        sa.Column("desired_state", sa.String(length=16), nullable=False),
        sa.Column("profile_name", sa.String(length=128), nullable=False),
        sa.Column("profile_digest", sa.String(length=71), nullable=False),
        sa.Column("current_allocation_id", sa.Uuid(), nullable=True),
        sa.Column("allocation_epoch", sa.BigInteger(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("protected_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delete_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("maintenance_action", sa.String(length=16), nullable=True),
        sa.Column("maintenance_token", sa.Uuid(), nullable=True),
        sa.Column(
            "maintenance_claimed_until",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "desired_state IN ('present', 'released', 'deleted')",
            name=op.f("ck_sandboxes_desired_state"),
        ),
        sa.CheckConstraint(
            "maintenance_action IS NULL OR maintenance_action IN ('release', 'destroy')",
            name=op.f("ck_sandboxes_maintenance_action"),
        ),
        sa.CheckConstraint(
            "workload_kind IN ('workspace', 'function')",
            name=op.f("ck_sandboxes_workload_kind"),
        ),
        sa.PrimaryKeyConstraint(
            "workload_kind", "logical_id", name=op.f("pk_sandboxes")
        ),
        sa.UniqueConstraint(
            "maintenance_token", name=op.f("uq_sandboxes_maintenance_token")
        ),
    )
    with op.batch_alter_table("sandboxes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_sandboxes_cleanup",
            [
                "desired_state",
                "last_used_at",
                "delete_after",
                "maintenance_claimed_until",
            ],
            unique=False,
        )

    op.create_table(
        "provider_admission",
        sa.Column("provider_scope", sa.String(length=256), nullable=False),
        sa.Column("max_active", sa.Integer(), nullable=False),
        sa.Column("active_count", sa.Integer(), nullable=False),
        sa.Column("reserved_count", sa.Integer(), nullable=False),
        sa.Column("create_tokens", sa.Float(), nullable=False),
        sa.Column("create_rate_per_second", sa.Float(), nullable=False),
        sa.Column("create_burst", sa.Integer(), nullable=False),
        sa.Column("token_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("blocked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("interactive_capacity_reserve", sa.Integer(), nullable=False),
        sa.Column("latency_capacity_reserve", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("provider_scope", name=op.f("pk_provider_admission")),
    )
    op.create_table(
        "workspace_storage",
        sa.Column("workload_kind", sa.String(length=16), nullable=False),
        sa.Column("logical_id", sa.Uuid(), nullable=False),
        sa.Column("provider_name", sa.String(length=32), nullable=False),
        sa.Column("storage_kind", sa.String(length=32), nullable=False),
        sa.Column("provider_storage_id", sa.String(length=256), nullable=True),
        sa.Column("bound_allocation_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("content_generation", sa.BigInteger(), nullable=False),
        sa.Column("delete_token", sa.Uuid(), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('provisioning', 'ready', 'migrating', 'deleting', 'deleted', 'error')",
            name=op.f("ck_workspace_storage_storage_state"),
        ),
        sa.CheckConstraint(
            "storage_kind IN ('volume', 'pvc', 'sandbox_native')",
            name=op.f("ck_workspace_storage_storage_kind"),
        ),
        sa.CheckConstraint(
            "workload_kind = 'workspace'",
            name=op.f("ck_workspace_storage_workspace_only"),
        ),
        sa.PrimaryKeyConstraint(
            "workload_kind", "logical_id", name=op.f("pk_workspace_storage")
        ),
        sa.UniqueConstraint(
            "delete_token", name=op.f("uq_workspace_storage_delete_token")
        ),
        sa.UniqueConstraint(
            "provider_name", "provider_storage_id", name="storage_provider_id"
        ),
    )
    op.create_table(
        "allocation_create_attempts",
        sa.Column("allocation_token", sa.Uuid(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("dispatch_state", sa.String(length=16), nullable=False),
        sa.Column("dispatch_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_request_id", sa.String(length=256), nullable=True),
        sa.Column("last_reconcile_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconcile_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "dispatch_state IN ('reserved', 'dispatched', 'acknowledged', 'unknown', 'resolved')",
            name=op.f("ck_allocation_create_attempts_dispatch_state"),
        ),
        sa.ForeignKeyConstraint(
            ["allocation_token"],
            ["allocations.allocation_token"],
            name=op.f("fk_allocation_create_attempts_allocation_token_allocations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "allocation_token", name=op.f("pk_allocation_create_attempts")
        ),
    )
    with op.batch_alter_table("allocation_create_attempts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_allocation_create_reconcile",
            ["dispatch_state", "reconcile_after"],
            unique=False,
        )

    op.create_table(
        "processes",
        sa.Column("workload_kind", sa.String(length=16), nullable=False),
        sa.Column("logical_id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("allocation_id", sa.Uuid(), nullable=False),
        sa.Column("allocation_epoch", sa.BigInteger(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("env_keys", sa.JSON(), nullable=False),
        sa.Column("cwd", sa.String(length=4096), nullable=False),
        sa.Column("tty", sa.Boolean(), nullable=False),
        sa.Column("output_limit_bytes", sa.Integer(), nullable=False),
        sa.Column("provider_process_id", sa.String(length=256), nullable=True),
        sa.Column("provider_tag", sa.String(length=256), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("output_tail", sa.Text(), nullable=True),
        sa.Column("truncated_before_seq", sa.BigInteger(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('reserved', 'starting', 'unknown', 'running', 'succeeded', 'failed', 'cancelled', 'timed_out')",
            name=op.f("ck_processes_process_state"),
        ),
        sa.CheckConstraint(
            "workload_kind IN ('workspace', 'function')",
            name=op.f("ck_processes_workload_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["allocations.allocation_id"],
            name=op.f("fk_processes_allocation_id_allocations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "workload_kind", "logical_id", "operation_id", name=op.f("pk_processes")
        ),
    )
    with op.batch_alter_table("processes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_processes_allocation", ["allocation_id", "state"], unique=False
        )

    op.create_table(
        "sessions",
        sa.Column("workload_kind", sa.String(length=16), nullable=False),
        sa.Column("logical_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("allocation_id", sa.Uuid(), nullable=False),
        sa.Column("allocation_epoch", sa.BigInteger(), nullable=False),
        sa.Column("provider_context_id", sa.String(length=256), nullable=True),
        sa.Column("cwd", sa.String(length=4096), nullable=False),
        sa.Column("env_keys", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('reserved', 'creating', 'unknown', 'active', 'stale', 'deleted')",
            name=op.f("ck_sessions_session_state"),
        ),
        sa.CheckConstraint(
            "workload_kind = 'workspace'", name=op.f("ck_sessions_workspace_only")
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["allocations.allocation_id"],
            name=op.f("fk_sessions_allocation_id_allocations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "workload_kind", "logical_id", "session_id", name=op.f("pk_sessions")
        ),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_sessions_allocation", ["allocation_id", "state"], unique=False
        )

    op.create_table(
        "python_executions",
        sa.Column("workload_kind", sa.String(length=16), nullable=False),
        sa.Column("logical_id", sa.Uuid(), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("allocation_id", sa.Uuid(), nullable=False),
        sa.Column("allocation_epoch", sa.BigInteger(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stdout", sa.Text(), nullable=False),
        sa.Column("stderr", sa.Text(), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("error_name", sa.String(length=256), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("traceback", sa.Text(), nullable=True),
        sa.Column("output_truncated", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('reserved', 'starting', 'unknown', 'succeeded', 'failed', 'timed_out')",
            name=op.f("ck_python_executions_python_execution_state"),
        ),
        sa.CheckConstraint(
            "workload_kind = 'workspace'",
            name=op.f("ck_python_executions_workspace_only"),
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["allocations.allocation_id"],
            name=op.f("fk_python_executions_allocation_id_allocations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "workload_kind",
            "logical_id",
            "operation_id",
            name=op.f("pk_python_executions"),
        ),
    )
    with op.batch_alter_table("python_executions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_python_executions_session", ["session_id", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("python_executions", schema=None) as batch_op:
        batch_op.drop_index("ix_python_executions_session")

    op.drop_table("python_executions")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_sessions_allocation")

    op.drop_table("sessions")
    with op.batch_alter_table("processes", schema=None) as batch_op:
        batch_op.drop_index("ix_processes_allocation")

    op.drop_table("processes")
    with op.batch_alter_table("allocation_create_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_allocation_create_reconcile")

    op.drop_table("allocation_create_attempts")
    op.drop_table("workspace_storage")
    op.drop_table("provider_admission")
    with op.batch_alter_table("sandboxes", schema=None) as batch_op:
        batch_op.drop_index("ix_sandboxes_cleanup")

    op.drop_table("sandboxes")
    with op.batch_alter_table("allocations", schema=None) as batch_op:
        batch_op.drop_index("ix_allocations_owner")

    op.drop_table("allocations")
    # ### end Alembic commands ###
