"""Surfaces the pod is reachable on, and the notifications it sends back."""

from __future__ import annotations

from typing import Any
from uuid import uuid4

from harness.run import a_name_for
from harness.drivers.api import items_of

JSON = dict[str, Any]


class SurfaceSteps:
    """Mixed into :class:`harness.world.Person`."""

    # --- surfaces --------------------------------------------------------

    async def platforms_available_to(self, pod: JSON) -> list[JSON]:
        return items_of(await self.api.get(f"/pods/{pod['id']}/available-surfaces"))

    async def surfaces_in(self, pod: JSON) -> list[JSON]:
        return items_of(await self.api.get(f"/pods/{pod['id']}/surfaces"))

    async def becomes_reachable_on_telegram(
        self,
        *,
        in_pod: JSON,
        agent: str,
        named: str = "tg",
        bot_token: str | None = None,
    ) -> JSON:
        """Install the connector, connect a bot, and put a surface on the pod.

        Three calls that are always made together and interesting on their own
        exactly once: that a surface connects at all is its own scenario, in
        `test_surfaces.py`. Everywhere else this is the setup a scenario needs
        before it can ask its actual question, and four copies of it drifted
        apart in the ways copies do.

        The bot token is unique per call because whatever stands in for Telegram
        remembers a webhook per token, and it outlives any one scenario.

        No `api_base_url`: the product talks to the real Telegram host and
        whatever answers for it — the proxy, or Telegram itself — is what
        answers. That is what lets this run with the SSRF guard at production
        strictness rather than a hole opened for the test.
        """
        organization = self.organization
        auth_config = await self.installs_connector(
            "telegram", in_organization=organization
        )
        account = await self.connects_account(
            in_organization=organization,
            auth_config=auth_config,
            credentials={"bot_token": bot_token or f"{uuid4().int % 10**10}:scenarios"},
        )
        return await self.connects_a_surface(
            in_pod=in_pod,
            platform="TELEGRAM",
            named=named,
            agent=agent,
            account=account,
        )

    async def connects_a_surface(
        self,
        *,
        in_pod: JSON,
        platform: str,
        named: str | None = None,
        unnamed: bool = False,
        agent: str | None = None,
        account: JSON | None = None,
        config: JSON | None = None,
    ) -> JSON:
        """Connect a surface, naming it unless the caller wants the plain call.

        A name is generated by default because a pod can hold several surfaces
        of one platform and the second needs one to avoid colliding with the
        first. ``unnamed=True`` sends no name at all, which is a different
        request rather than a tidier one: for email it means "connect the
        address this agent already has" — the call the product's own UI makes —
        while a named one asks for a distinct surface. Naming by default is
        exactly what hid that difference.
        """
        body: JSON = {"platform": platform}
        if not unnamed:
            body["name"] = named or a_name_for("surface")
        if agent:
            body["default_agent_name"] = agent
        if account is not None:
            # Where the bot's credentials come from. Without it the platform has
            # nothing to authenticate as, and creation is refused.
            body["account_id"] = str(account["id"])
        if config is not None:
            body["config"] = config
        return await self.api.post(
            f"/pods/{in_pod['id']}/surfaces",
            what=f"{self.label} connecting a {platform} surface",
            json=body,
        )

    async def is_refused_connecting_a_surface(
        self, *, in_pod: JSON, platform: str, config: JSON | None = None
    ) -> int:
        response = await self.api.call(
            "POST",
            f"/pods/{in_pod['id']}/surfaces",
            json={
                "platform": platform,
                "name": a_name_for("surface"),
                **({"config": config} if config is not None else {}),
            },
        )
        if response.status_code < 400:
            raise AssertionError(
                f"{self.label} was expected to be refused connecting a "
                f"{platform} surface, but it succeeded ({response.status_code})"
            )
        return response.status_code

    async def opens_surface(self, name: str, *, in_pod: JSON) -> JSON:
        return await self.api.get(f"/pods/{in_pod['id']}/surfaces/{name}")

    async def deletes_surface(self, name: str, *, in_pod: JSON) -> None:
        await self.api.delete(
            f"/pods/{in_pod['id']}/surfaces/{name}",
            what=f"{self.label} deleting surface {name!r}",
        )

    async def setup_state_of(self, name: str, *, in_pod: JSON) -> JSON:
        return await self.api.get(f"/pods/{in_pod['id']}/surfaces/{name}/setup")

    async def setup_guide_for(self, platform: str, *, in_pod: JSON) -> JSON:
        return await self.api.get(f"/pods/{in_pod['id']}/surface-setup/{platform}")

    async def my_surfaces(self) -> list[JSON]:
        return items_of(await self.api.get("/surfaces/me"))

    # --- notifications ---------------------------------------------------

    async def notifies(
        self,
        person: Any,
        *,
        in_pod: JSON,
        title: str = "Something needs you",
        body: str = "Please take a look.",
        expects_response: bool = False,
    ) -> JSON:
        return await self.api.post(
            f"/pods/{in_pod['id']}/notifications",
            what=f"{self.label} notifying {person.label}",
            json={
                # A plain string: pod member id, user id, or email.
                "recipient": person.email,
                "title": title,
                "body": body,
                "expects_response": expects_response,
            },
        )

    async def notifications_in(self, pod: JSON, **query: Any) -> list[JSON]:
        return items_of(
            await self.api.get(f"/pods/{pod['id']}/notifications", params=query or None)
        )

    async def unread_count_in(self, pod: JSON) -> int:
        payload = await self.api.get(f"/pods/{pod['id']}/notifications/unread-count")
        for key in ("count", "unread", "unread_count", "total"):
            if key in payload:
                return int(payload[key])
        raise AssertionError(f"no unread count in {payload}")

    async def reads(self, notification: JSON, *, in_pod: JSON) -> JSON:
        return await self.api.post(
            f"/pods/{in_pod['id']}/notifications/{notification['id']}/read",
            what=f"{self.label} reading a notification",
        )

    async def reads_everything_in(self, pod: JSON) -> JSON:
        return await self.api.post(f"/pods/{pod['id']}/notifications/read-all")

    async def acknowledges(self, notification: JSON, *, in_pod: JSON) -> JSON:
        return await self.api.post(
            f"/pods/{in_pod['id']}/notifications/{notification['id']}/acknowledge"
        )

    async def answers(self, notification: JSON, *, saying: str, in_pod: JSON) -> JSON:
        return await self.api.post(
            f"/pods/{in_pod['id']}/notifications/{notification['id']}/respond",
            what=f"{self.label} answering a notification",
            json={"summary": saying},
        )

    async def is_refused_answering(
        self, notification: JSON, *, saying: str, in_pod: JSON
    ) -> int:
        response = await self.api.call(
            "POST",
            f"/pods/{in_pod['id']}/notifications/{notification['id']}/respond",
            json={"summary": saying},
        )
        if response.status_code < 400:
            raise AssertionError(
                f"{self.label} was expected to be refused answering this "
                f"notification, but it was accepted ({response.status_code})"
            )
        return response.status_code

    async def changes_surface(self, name: str, *, in_pod: JSON, **changes: Any) -> JSON:
        return await self.api.patch(
            f"/pods/{in_pod['id']}/surfaces/{name}",
            what=f"{self.label} updating surface {name!r}",
            json=changes,
        )

    async def channels_of(self, name: str, *, in_pod: JSON) -> Any:
        return await self.api.call(
            "GET", f"/pods/{in_pod['id']}/surfaces/{name}/channels"
        )

    async def slack_manifest(self, *, for_agent: str | None = None) -> Any:
        return await self.api.call(
            "GET",
            "/surface-setup/slack/manifest",
            params={"agent_name": for_agent} if for_agent else None,
        )

    async def makes_default_surface(self, surface: JSON, *, platform: str) -> Any:
        return await self.api.call(
            "PUT",
            "/surfaces/me/default",
            json={"platform": platform, "surface_id": str(surface["id"])},
        )
